site_name: Notes
site_author: Ander Aaen Springborg
site_url: https://andersspringborg.github.io/notes/
repo_name: 'AndersSpringborg/notes'
repo_url: 'https://github.com/AndersSpringborg/notes'


theme:
    name: 'material'
    font: 
        text: 'Open Sans'
        code: 'Roboto Mono'
    icon:
        logo: material/school
        repo: fontawesome/brands/github
    features:
        - tabs

plugins:
  - search
  - git-revision-date-localized

extra_css:
  # - 'stylesheets/github.css'
  # - 'stylesheets/github.user.css'
  # - 'stylesheets/extra.css'


extra_javascript:
  # - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML'


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
