site_name: Notes
site_description: 'Mine noteer på software'
site_author: 'Anders Aaen Springborg'
docs_dir: docs/
repo_name: 'AndersSpringborg/notes'
repo_url: 'https://github.com/AndersSpringborg/notes'
nav:
    - Home: index.md
theme:
    name: 'material'
    font: 
        text: 'Open Sans'
        code: 'Roboto Mono'
    icon:
        logo: material/school
        repo: fontawesome/brands/github
    features:
        - tabs

#lugins:
# - search
# - git-revision-date-localized

#xtra_css:
  # - 'stylesheets/github.css'
  # - 'stylesheets/github.user.css'
  # 'stylesheets/extra.css'


#extra_javascript:
#   - 'javascripts/extra.js'
#   - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML'


#arkdown_extensions:
# - admonition
#  - codehilite:
#     guess_lang: false
#     linenums: true
# - toc:
#     permalink: true
# - pymdownx.arithmatex
# - pymdownx.emoji
# - pymdownx.tasklist:
#     custom_checkbox: true
#
